### ISSUE TITLE
Content '{0}' not found at path: '' when loading state json

### ISSUE THREAD

**Issue by rabidgremlin** [bladecoder/blade-ink#2]
Hiya,

I'm trying to save/restore a game but I'm getting a _Content '{0}' not found at path: ''_ exception when calling the loadJson() on the StoryState object.

Stracktrace:

```
com.bladecoder.ink.runtime.StoryException: Content '{0}' not found at path: ''
	at com.bladecoder.ink.runtime.Container.contentWithPathComponent(Container.java:262)
	at com.bladecoder.ink.runtime.Container.contentAtPath(Container.java:282)
	at com.bladecoder.ink.runtime.Container.contentAtPath(Container.java:268)
	at com.bladecoder.ink.runtime.Story.contentAtPath(Story.java:329)
	at com.bladecoder.ink.runtime.CallStack$Thread.<init>(CallStack.java:116)
	at com.bladecoder.ink.runtime.CallStack.setJsonToken(CallStack.java:316)
	at com.bladecoder.ink.runtime.StoryState.setJsonToken(StoryState.java:501)
	at com.bladecoder.ink.runtime.StoryState.loadJson(StoryState.java:270)
	at TestLoadSave.testLoadSave(TestLoadSave.java:116)
```

Test that is failing looks like:

```
    @Test
	public void testLoadSave() throws Exception
	{
		Story story = new Story(inkStoryJson);

		String storyText = getContinueText(story);
		assertThat(storyText, is("We arrived into London at 9.45pm exactly.\n"));

		String choicesText = getChoicesText(story);
		assertThat(choicesText, is("0:\"There is not a moment to lose!\"\n1:\"Monsieur, let us savour this moment!\"\n2:We hurried home\n"));
		
		// save the game state
		String saveString = story.getState().toJson();

		// recreate game and load state
		story = new Story(inkStoryJson);		
		story.getState().loadJson(saveString);

		story.chooseChoiceIndex(0);

		storyText = getContinueText(story);
		assertThat(storyText, is("\"There is not a moment to lose!\" I declared.\nWe hurried home to Savile Row  as fast as we could.\n"));

		// check that we are at the end
		assertThat(story.canContinue(), is(false));
		assertThat(story.getCurrentChoices().size(), is(0));
	}
```

Ink source is:

```
=== back_in_london ===

We arrived into London at 9.45pm exactly.

*   "There is not a moment to lose!"[] I declared.
    -> hurry_outside 

*   "Monsieur, let us savour this moment!"[] I declared.
    My master clouted me firmly around the head and dragged me out of the door. 
    -> dragged_outside 

*   [We hurried home] -> hurry_outside


=== hurry_outside ===
We hurried home to Savile Row -> as_fast_as_we_could


=== dragged_outside === 
He insisted that we hurried home to Savile Row 
-> as_fast_as_we_could


=== as_fast_as_we_could === 
<> as fast as we could.
-> END
```

Any ideas ?

Thanks

Jonathan

Test project: [testink.zip](https://github.com/bladecoder/blade-ink/files/481236/testink.zip)

**Comment by bladecoder** [comment]
Fixed with the latest commit!

**Comment by rabidgremlin** [comment]
Awesome! Any chance of pushing a new release (or snapshot) to Maven central ?

**Comment by bladecoder** [comment]
Yes! Uploaded v0.1.2 to Maven central.
