### ISSUE TITLE
Exception when making a threaded choice after loading StoryState JSON

### ISSUE THREAD

**Issue by danwilhelm** [bladecoder/blade-ink#6]
It seems that the StoryState object may not always be properly converted to/from JSON -- particularly when involving threaded choices.

**To reproduce the exception:**
1. Define some choice points within a thread. (see Example below)

2. Convert the StoryState to JSON then load the JSON back into the StoryState.

3. Select a threaded choice via chooseChoiceIndex(), then continueMaximally().

**Example:**
Here is an example of a threaded choice:

```
// 'inkfiles/threads/thread-bug.ink'

-> start

=== start ===
Here is some gold. Do you want it?
- (top)
    <- choices(-> top)
    + Yes
        You win!
        -> END

=== choices(-> goback) ===
+ No
    Try again!
    -> goback
```

Here is blade-ink code that throws an exception, using the above ink file:

```
String json = TestUtils.getJsonString("inkfiles/threads/thread-bug.ink.json");
Story story = new Story(json);

System.out.println(story.continueMaximally());

// Convert state to JSON then load it back in
String stateJson = story.getState().toJson();
story.getState().loadJson(stateJson);

// + Works correctly if choiceIdx is 1 ('Yes', defined in the knot)
// + Throws exception if choiceIdx is 0 ('No', defined in the thread)
story.chooseChoiceIndex(0);
System.out.println(story.continueMaximally());
```

This code yields the following exception:

```
java.lang.Exception: RUNTIME ERROR: Variable 'goback' could not be found in context '-1'. This shouldn't be possible so is a bug in the ink engine. Please try to construct a minimal story that reproduces the problem and report to inkle, thank you!

	at com.bladecoder.ink.runtime.VariablesState.getRawVariableWithName(VariablesState.java:157)
	at com.bladecoder.ink.runtime.VariablesState.getVariableWithName(VariablesState.java:168)
	at com.bladecoder.ink.runtime.VariablesState.getVariableWithName(VariablesState.java:164)
	at com.bladecoder.ink.runtime.Story.performLogicAndFlowControl(Story.java:1086)
	at com.bladecoder.ink.runtime.Story.step(Story.java:1708)
	at com.bladecoder.ink.runtime.Story.continueInternal(Story.java:463)
	at com.bladecoder.ink.runtime.Story.Continue(Story.java:425)
	at com.bladecoder.ink.runtime.Story.continueMaximally(Story.java:598)
	at com.bladecoder.ink.runtime.test.ThreadSpecTest.testThreadBug(ThreadSpecTest.java:31)
```

**Comment by bladecoder** [comment]
This error is also reproduced in the reference Inkle C# engine. I reported the bug there.

https://github.com/inkle/ink/issues/267

I will apply their solution in the Java version when it is fixed in the C# engine.

Cheers!

**Comment by bladecoder** [comment]
Fixed!

**Comment by danwilhelm** [comment]
Thanks again -- I really appreciate the fast turnaround and submitting it to Ink. 

Cheers!
