### ISSUE TITLE
Simple run error

### ISSUE THREAD

**Issue by DranikProgrammer** [bladecoder/blade-ink#8]
`

{"inkVersion":16,"root":["Hello World1!","\n","done",{"#f":3}],"listDefs":{}}
java.lang.Exception: Unhandled RTObject type in JSON: ﻿{"inkVersion":16,"root":["Hel
        at com.bladecoder.ink.runtime.SimpleJson$Reader.readObject(SimpleJson.java:151)
        at com.bladecoder.ink.runtime.SimpleJson$Reader.<init>(SimpleJson.java:25)
        at com.bladecoder.ink.runtime.SimpleJson.textToHashMap(SimpleJson.java:292)
        at com.bladecoder.ink.runtime.Story.<init>(Story.java:105)
        at com.gdxgame.stories.StoryTest.create(StoryTest.java:54)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at com.gdxgame.stories.StoryTest.create(StoryTest.java:61)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

`

Ink file 
`
Hello World1!
`

Generated Json
`
{"inkVersion":16,"root":["^Hello World1!","\n","done",{"#f":3}],"listDefs":{}}
`

Code is the same as in the tutorial. I'm using it with LibGdx

I hope you'll fix it or tell me what I'm doing wrong.
Thanks !

**Comment by DranikProgrammer** [comment]
Sorry I noticed my error ...
I was using libgdx's file loading and forgot to do this 

replace('\uFEFF', ' ')

Sorry !
